import type { AdminStats, Article, Book, Course, Exam, StudentStats } from './types';

export const MAIN_CATEGORIES_DATA = [
  {
    title: 'Academic Maths',
    description: 'School & College curriculum',
    color: 'text-[#F59E0B]',
    order: 1,
    subCategories: ['Standard One-Seven', 'Standard Eight-Ten', 'SSC Mathematics', 'HSC Higher Mathematics', 'O Level', 'A Level'],
  },
  {
    title: 'Olympiad',
    description: 'Problem Solving & competition',
    color: 'text-[#2563EB]',
    order: 2,
    subCategories: ['Primary Level', 'Junior Level', 'Secondary Level', 'Higher Secondary Level', 'Problem Solving', 'Number Theory', 'Geometry', 'Combinatorics', 'Algebra'],
  },
  {
    title: 'Admission Course',
    description: 'University & job admission prep',
    color: 'text-[#10B981]',
    order: 3,
    subCategories: ['University Admission Math', 'Engineering Admission Math', 'Medical Admission Math', 'GST Admission Math', 'IBA/BBA Math', 'Written Math Preparation', 'Shortcut Math & Problem Solving'],
  },
  {
    title: 'Books Corner',
    description: 'Book resources & practice',
    color: 'text-purple-400',
    order: 4,
    subCategories: ['Academic Books', 'Olympiad Books', 'Admission Books', 'Practice Books', 'Formula Sheets', 'PDF Resources', 'Model Test Books'],
  },
  {
    title: 'Mathematics and Nature',
    description: 'Articles, visuals & real-life math',
    color: 'text-rose-400',
    order: 5,
    subCategories: ['Fibonacci Sequence', 'Golden Ratio', 'Symmetry', 'Fractals', 'Geometry in Nature', 'Mathematical Patterns', 'Real-life Mathematics'],
  },
];

export const courses: Course[] = [
  {
    id: '1',
    title: 'Standard One–Seven Foundation Mathematics',
    instructor: 'Mathemzi Edu Mentor',
    price: 1200,
    duration: '8 Weeks',
    lessons: 32,
    rating: 4.7,
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'Standard One-Seven',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    description: 'Build a strong mathematics foundation for primary and junior secondary students with structured lessons, practice exercises, and step-by-step explanations.',
    level: 'Beginner',
    enrolled: 0,
    outcomes: [
      'Strong arithmetic and number sense',
      'Basic algebra and geometry fundamentals',
      'Problem solving confidence',
      'Weekly practice tests and progress tracking',
    ],
    curriculum: [
      { title: 'Number Systems & Place Value', lessons: 6, time: '1h 50m' },
      { title: 'Addition, Subtraction, Multiplication & Division', lessons: 8, time: '2h 30m' },
      { title: 'Introduction to Fractions & Decimals', lessons: 6, time: '1h 45m' },
      { title: 'Basic Geometry & Measurement', lessons: 6, time: '2h 00m' },
      { title: 'Word Problems & Applications', lessons: 6, time: '1h 40m' },
    ],
  },
  {
    id: '2',
    title: 'SSC Mathematics Complete Course',
    instructor: 'Prof. Anisul Islam',
    price: 1500,
    duration: '12 Weeks',
    lessons: 48,
    rating: 4.6,
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'SSC Mathematics',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1600&auto=format&fit=crop',
    description: 'Complete SSC Mathematics syllabus coverage with board-focused examples, model tests, and real-world applications for exam success.',
    level: 'Intermediate',
    enrolled: 0,
    outcomes: [
      'Full SSC math syllabus mastery',
      'Board exam question pattern practice',
      'Step-by-step written answer techniques',
      'Weekly model tests with explanations',
    ],
    curriculum: [
      { title: 'Algebra & Equations', lessons: 10, time: '3h 50m' },
      { title: 'Geometry & Trigonometry', lessons: 12, time: '4h 20m' },
      { title: 'Statistics & Probability', lessons: 8, time: '3h 00m' },
      { title: 'Full Mock Tests & Review', lessons: 8, time: '3h 10m' },
    ],
  },
  {
    id: '3',
    title: 'HSC Higher Mathematics Foundation',
    instructor: 'Prof. Anisul Islam',
    price: 2000,
    duration: '12 Weeks',
    lessons: 48,
    rating: 4.7,
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'HSC Higher Mathematics',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    description: 'Master HSC Higher Mathematics with detailed calculus, coordinate geometry, algebra, and board pattern exam preparation.',
    level: 'Advanced',
    enrolled: 0,
    outcomes: [
      'Full HSC Higher Math syllabus coverage',
      'Calculus and coordinate geometry mastery',
      'Board-style written answer patterns',
      'Weekly model test review',
    ],
    curriculum: [
      { title: 'Functions & Graphs', lessons: 8, time: '3h 00m' },
      { title: 'Differentiation', lessons: 12, time: '4h 30m' },
      { title: 'Integration', lessons: 12, time: '4h 30m' },
      { title: 'Full Mock Tests & Review', lessons: 8, time: '3h 00m' },
    ],
  },
  {
    id: '4',
    title: 'O Level Mathematics Preparation',
    instructor: 'Mathemzi Edu Mentor',
    price: 2500,
    duration: '10 Weeks',
    lessons: 40,
    rating: 4.5,
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'O Level',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1600&auto=format&fit=crop',
    description: 'Cambridge O Level Mathematics complete preparation covering all topics, past paper practice, and exam techniques.',
    level: 'Intermediate',
    enrolled: 0,
    outcomes: [
      'Complete O Level syllabus coverage',
      'Past paper solving strategies',
      'Scientific calculator skills',
      'Cambridge exam technique mastery',
    ],
    curriculum: [
      { title: 'Number, Algebra & Graphs', lessons: 12, time: '3h 40m' },
      { title: 'Geometry & Mensuration', lessons: 10, time: '3h 15m' },
      { title: 'Trigonometry & Vectors', lessons: 8, time: '2h 50m' },
      { title: 'Past Paper Practice', lessons: 10, time: '3h 30m' },
    ],
  },
  {
    id: '5',
    title: 'A Level Pure Mathematics Starter',
    instructor: 'Prof. Anisul Islam',
    price: 3000,
    duration: '12 Weeks',
    lessons: 52,
    rating: 4.8,
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'A Level',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    description: 'A Level Pure Mathematics 1 & 2 complete preparation with rigorous proof-based approach, past papers, and exam strategies.',
    level: 'Advanced',
    enrolled: 0,
    outcomes: [
      'A Level Pure Math full syllabus coverage',
      'Proof-based mathematical reasoning',
      'CIE/Edexcel exam techniques',
      'Past paper mastery with detailed solutions',
    ],
    curriculum: [
      { title: 'Functions, Quadratics & Inequalities', lessons: 8, time: '3h 30m' },
      { title: 'Coordinate Geometry', lessons: 6, time: '2h 20m' },
      { title: 'Trigonometry', lessons: 10, time: '4h 00m' },
      { title: 'Differentiation & Integration', lessons: 14, time: '5h 20m' },
      { title: 'Series, Logs & Exponentials', lessons: 8, time: '3h 00m' },
    ],
  },
  {
    id: '6',
    title: 'Junior Math Olympiad Preparation',
    instructor: 'Dr. Hasan Rahman',
    price: 2000,
    duration: '8 Weeks',
    lessons: 36,
    rating: 4.9,
    category: 'Olympiad',
    mainCategory: 'Olympiad',
    subCategory: 'Junior Level',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    description: 'Prepare for junior-level math olympiads with problem-solving techniques, mock contests, and step-by-step guidance for std 6-8 students.',
    level: 'Intermediate',
    enrolled: 0,
    outcomes: [
      'Number theory problem solving',
      'Combinatorics fundamentals',
      'Geometry proof techniques',
      'Timed olympiad practice sessions',
    ],
    curriculum: [
      { title: 'Number Theory Foundations', lessons: 8, time: '2h 50m' },
      { title: 'Algebraic Problem Solving', lessons: 8, time: '2h 50m' },
      { title: 'Geometry & Proofs', lessons: 8, time: '3h 00m' },
      { title: 'Mock Olympiad Contests', lessons: 6, time: '2h 20m' },
    ],
  },
  {
    id: '7',
    title: 'Secondary Math Olympiad Problem Solving',
    instructor: 'Dr. Hasan Rahman',
    price: 2500,
    duration: '10 Weeks',
    lessons: 40,
    rating: 4.8,
    category: 'Olympiad',
    mainCategory: 'Olympiad',
    subCategory: 'Secondary Level',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    description: 'Advanced olympiad training for secondary students covering the four core olympiad areas with competition-level practice.',
    level: 'Advanced',
    enrolled: 0,
    outcomes: [
      'Advanced number theory and combinatorics',
      'Geometry proof strategy',
      'Algebra manipulation techniques',
      'National olympiad preparation',
    ],
    curriculum: [
      { title: 'Number Theory — Advanced', lessons: 8, time: '3h 10m' },
      { title: 'Combinatorics & Counting', lessons: 8, time: '3h 00m' },
      { title: 'Geometry — Circle & Triangle', lessons: 8, time: '3h 20m' },
      { title: 'Algebra — Inequalities', lessons: 8, time: '3h 00m' },
    ],
  },
  {
    id: '8',
    title: 'Engineering Admission Math Crash Course',
    instructor: 'Ayesha Siddiqua',
    price: 2000,
    duration: '10 Weeks',
    lessons: 40,
    rating: 4.9,
    category: 'Admission Course',
    mainCategory: 'Admission Course',
    subCategory: 'Engineering Admission Math',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1600&auto=format&fit=crop',
    description: 'Focused engineering admission math preparation for BUET, KUET, CUET, and DU engineering units with shortcut techniques and previous-year solutions.',
    level: 'Advanced',
    enrolled: 0,
    outcomes: [
      'Fast arithmetic and mental math',
      'Question pattern recognition',
      'Previous-year solution breakdown',
      'Mock test time management',
    ],
    curriculum: [
      { title: 'Arithmetic Speed Systems', lessons: 8, time: '3h 00m' },
      { title: 'Algebra & Geometry Shortcuts', lessons: 10, time: '3h 50m' },
      { title: 'Calculus Quick Problem Solving', lessons: 6, time: '2h 20m' },
      { title: 'Full Mock Analysis & Strategy', lessons: 8, time: '3h 00m' },
    ],
  },
];

export const exams: Exam[] = [
  {
    id: 'exam1',
    title: 'SSC Mathematics Model Test 2026',
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'SSC Mathematics',
    type: 'MCQ',
    fee: 100,
    date: '2026-12-15',
    duration: '60 Mins',
    totalMarks: 50,
    syllabus: 'Algebra, Geometry, Trigonometry, Statistics',
    description: 'Full SSC math syllabus model test with 50 MCQs. Auto-graded with instant results and detailed explanations.',
    isPublished: true,
    createdAt: Date.now(),
  },
  {
    id: 'exam2',
    title: 'HSC Higher Math MCQ Practice',
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'HSC Higher Mathematics',
    type: 'MCQ',
    fee: 150,
    date: '2026-12-20',
    duration: '90 Mins',
    totalMarks: 60,
    syllabus: 'Differentiation, Integration, Coordinate Geometry',
    description: 'HSC Higher Mathematics MCQ practice test covering calculus, coordinate geometry, and key board exam topics.',
    isPublished: true,
    createdAt: Date.now(),
  },
  {
    id: 'exam3',
    title: 'Junior Olympiad Mock Test',
    category: 'Olympiad',
    mainCategory: 'Olympiad',
    subCategory: 'Junior Level',
    type: 'MCQ',
    fee: 50,
    date: '2026-12-22',
    duration: '60 Mins',
    totalMarks: 40,
    syllabus: 'Number Theory, Algebra, Basic Geometry',
    description: 'Junior-level math olympiad mock test with problem-solving questions for students in classes 6-8.',
    isPublished: true,
    createdAt: Date.now(),
  },
  {
    id: 'exam4',
    title: 'Secondary Olympiad Problem Solving Test',
    category: 'Olympiad',
    mainCategory: 'Olympiad',
    subCategory: 'Secondary Level',
    type: 'Written',
    fee: 100,
    date: '2026-12-25',
    duration: '120 Mins',
    totalMarks: 100,
    syllabus: 'Number Theory, Combinatorics, Geometry, Algebra',
    description: 'Full secondary olympiad written test with proof-based problems. Admin-reviewed with detailed feedback.',
    isPublished: true,
    createdAt: Date.now(),
  },
  {
    id: 'exam5',
    title: 'Engineering Admission Math Practice Test',
    category: 'Admission Course',
    mainCategory: 'Admission Course',
    subCategory: 'Engineering Admission Math',
    type: 'MCQ',
    fee: 80,
    date: '2026-12-28',
    duration: '45 Mins',
    totalMarks: 40,
    syllabus: 'Algebra, Geometry, Calculus, Probability',
    description: 'Engineering admission-style MCQ test with shortcut-solving techniques and time management practice.',
    isPublished: true,
    createdAt: Date.now(),
  },
];

export const articles: Article[] = [
  {
    id: 'a1',
    title: 'How to Build a Strong Foundation in Mathematics',
    description: 'A step-by-step guide for students to develop core mathematical skills from an early age.',
    author: 'Mathemzi Edu Editorial',
    date: 'Oct 12, 2026',
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'Standard One-Seven',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    content: 'Building a strong foundation in mathematics starts early. Young learners need more than memorization — they need to understand the "why" behind each concept.\n\nHere are the key steps to build mathematical confidence from the beginning:\n\n1. Master Number Sense: Understand place value, counting, and basic operations deeply before moving to advanced topics.\n\n2. Practice Daily: Short, focused practice sessions (20-30 minutes) are far more effective than long, irregular study marathons.\n\n3. Real-life Connections: Connect math to everyday situations — shopping, cooking, measuring — to make it meaningful.\n\n4. Learn from Mistakes: Every wrong answer is an opportunity to understand a misconception. Review errors carefully.\n\n5. Use Visual Models: Drawings, diagrams, and physical objects help abstract concepts become concrete.\n\nAt Mathemzi Edu, our foundation courses are designed to help students develop these essential skills through structured, engaging content.',
  },
  {
    id: 'a2',
    title: 'Why Practice Exams Improve Math Confidence',
    description: 'How regular mock tests and timed practice build exam readiness and reduce math anxiety.',
    author: 'Prof. Anisul Islam',
    date: 'Oct 18, 2026',
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'SSC Mathematics',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1600&auto=format&fit=crop',
    content: 'Many students know the material but struggle during exams. The issue is not knowledge — it is exam readiness.\n\nPractice exams solve several problems at once:\n\n1. Time Management: Students learn to allocate time across questions and avoid getting stuck on a single problem.\n\n2. Pattern Recognition: After 5-6 mock tests, students begin to recognize question patterns and common trap answers.\n\n3. Anxiety Reduction: Familiarity with exam format reduces nervousness. The exam feels like "just another practice test."\n\n4. Gap Identification: Mock tests reveal exactly which topics need more work, so study time is used efficiently.\n\n5. Confidence Building: Seeing improvement across mock tests builds genuine self-belief.\n\nMathemzi Edu offers MCQ and written practice exams at every level — SSC, HSC, O Level, A Level, Olympiad, and admission tests. Every exam gives instant results, detailed feedback, and progress tracking.',
  },
  {
    id: 'a3',
    title: 'How to Prepare for Math Olympiad in Bangladesh',
    description: 'A comprehensive roadmap for Bangladeshi students aiming for national and international math olympiads.',
    author: 'Dr. Hasan Rahman',
    date: 'Nov 01, 2026',
    category: 'Olympiad',
    mainCategory: 'Olympiad',
    subCategory: 'Secondary Level',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    content: 'The Bangladesh Mathematical Olympiad (BdMO) is the gateway to the International Mathematical Olympiad (IMO). Here is a structured preparation roadmap:\n\nStage 1 — Foundation (3-4 months):\nMaster the four core olympiad areas: Number Theory, Algebra, Geometry, and Combinatorics. Use standard olympiad textbooks and solve beginner problems daily.\n\nStage 2 — Intermediate Problem Solving (3-4 months):\nMove to national-level problems. Learn proof techniques: induction, contradiction, pigeonhole principle, and invariants.\n\nStage 3 — Mock Contests (2-3 months):\nTake full-length timed contests weekly. Review every solution in detail — especially the problems you could not solve.\n\nKey Resources:\n- Bangladesh Math Olympiad past papers\n- Art of Problem Solving (AoPS) materials\n- Geometry Revisited (Coxeter & Greitzer)\n- Mathemzi Edu olympiad courses and mock tests\n\nAt Mathemzi Edu, our olympiad courses are designed by national-level competitors who understand exactly what it takes to succeed at BdMO.',
  },
  {
    id: 'a4',
    title: 'Mathematics in Nature: Patterns Around Us',
    description: 'Explore Fibonacci sequences, golden ratios, and fractal geometry in the natural world.',
    author: 'Mathemzi Edu Editorial',
    date: 'Nov 15, 2026',
    category: 'Mathematics and Nature',
    mainCategory: 'Mathematics and Nature',
    subCategory: 'Fibonacci Sequence',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1600&auto=format&fit=crop',
    content: 'Mathematics is not just in textbooks — it is all around us. From the spiral of a galaxy to the arrangement of seeds in a sunflower, mathematical patterns shape our world.\n\nFibonacci Sequence (0, 1, 1, 2, 3, 5, 8, 13, 21...):\nThis sequence appears in pinecones, sunflower heads, nautilus shells, and even the branching of trees. Each number is the sum of the two before it, creating an efficient growth pattern optimized by nature.\n\nGolden Ratio (φ ≈ 1.618):\nDerived from the Fibonacci sequence, the golden ratio appears in the proportions of the human face, ancient architecture, and Renaissance art. It is often called nature\'s aesthetic number.\n\nFractals:\nFractals are infinitely repeating patterns that look the same at any scale. Snowflakes, fern leaves, lightning bolts, and blood vessels all display fractal geometry. Benoit Mandelbrot formalized fractal mathematics to describe these "rough" natural shapes.\n\nUnderstanding these patterns helps students see mathematics not as abstract rules but as the language in which nature is written.',
  },
  {
    id: 'a5',
    title: 'SSC Math Preparation Strategy — 2026 Guide',
    description: 'A practical month-by-month preparation plan for SSC Mathematics board exam success.',
    author: 'Prof. Anisul Islam',
    date: 'Dec 01, 2026',
    category: 'Academic Maths',
    mainCategory: 'Academic Maths',
    subCategory: 'SSC Mathematics',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1600&auto=format&fit=crop',
    content: 'The SSC Mathematics exam requires both conceptual understanding and exam technique. Here is a proven preparation plan:\n\nMonth 1-2 — Foundation:\nReview all chapters from Class 9-10 textbook. Focus on core concepts: algebra, geometry, trigonometry, and statistics. Complete every example problem in the textbook.\n\nMonth 3-4 — Practice:\nSolve board exam questions from the last 5 years. Time yourself. Learn to write clear, step-by-step solutions — SSC markers award partial credit for method even when the final answer is wrong.\n\nMonth 5 — Model Tests:\nTake full-length model tests under exam conditions. Review every mistake. Keep a "mistake notebook" to track patterns in your errors.\n\nFinal Month — Revision:\nGo through the mistake notebook. Solve the most recent board papers again. Focus on your weakest 3-4 topics.\n\nMathemzi Edu\'s SSC Mathematics Complete Course includes all these elements with structured lessons, topic-wise practice, and full mock tests.',
  },
  {
    id: 'a6',
    title: 'Admission Math Preparation Roadmap',
    description: 'How to prepare for engineering, medical, and university admission math tests in Bangladesh.',
    author: 'Ayesha Siddiqua',
    date: 'Dec 10, 2026',
    category: 'Admission Course',
    mainCategory: 'Admission Course',
    subCategory: 'Engineering Admission Math',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1600&auto=format&fit=crop',
    content: 'Admission tests in Bangladesh — BUET, KUET, DU, medical colleges — require speed, accuracy, and strategic preparation.\n\nKey Differences from Board Exams:\n1. Speed matters: Most admission tests have 40-60 MCQs in under an hour.\n2. Negative marking: Guessing hurts. You need both knowledge and test strategy.\n3. Shortcut math: You cannot solve every problem the long way. Mental math and shortcuts are essential.\n\nPreparation Strategy:\n- Complete the HSC syllabus thoroughly first (board concepts are the foundation).\n- Practice 100+ MCQs daily during the admission season.\n- Learn shortcut techniques: Vedic math, approximation strategies, elimination methods.\n- Take weekly mock tests under strict time limits.\n- Analyze every wrong answer — understand why the correct option is correct and why each distractor is wrong.\n\nMathemzi Edu\'s Engineering Admission Math Crash Course combines all these elements with focused topic coverage, shortcut training, and full mock tests.',
  },
];

export const books: Book[] = [
  {
    id: 'b1',
    title: 'SSC Math Formula Handbook',
    author: 'Prof. Anisul Islam',
    description: 'Complete SSC Mathematics formula reference covering algebra, geometry, trigonometry, and statistics with worked examples.',
    category: 'Academic Books',
    mainCategory: 'Books Corner',
    subCategory: 'Academic Books',
    classOrLevel: 'SSC / Class 9-10',
    price: 250,
    isFree: false,
    coverImage: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'b2',
    title: 'HSC Higher Math Practice Book',
    author: 'Prof. Anisul Islam',
    description: '500+ practice problems for HSC Higher Mathematics First and Second Paper with step-by-step solutions.',
    category: 'Academic Books',
    mainCategory: 'Books Corner',
    subCategory: 'Academic Books',
    classOrLevel: 'HSC / Class 11-12',
    price: 450,
    isFree: false,
    coverImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'b3',
    title: 'Junior Math Olympiad Problem Book',
    author: 'Dr. Hasan Rahman',
    description: '300+ olympiad problems for junior-level students (Class 6-8) with categorized solutions and strategy notes.',
    category: 'Olympiad Books',
    mainCategory: 'Books Corner',
    subCategory: 'Olympiad Books',
    classOrLevel: 'Junior / Class 6-8',
    price: 0,
    isFree: true,
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    downloadUrl: '#',
  },
  {
    id: 'b4',
    title: 'Secondary Olympiad Geometry Guide',
    author: 'Dr. Hasan Rahman',
    description: 'Complete geometry problem-solving guide for secondary-level olympiad aspirants with proof techniques and 200+ problems.',
    category: 'Olympiad Books',
    mainCategory: 'Books Corner',
    subCategory: 'Olympiad Books',
    classOrLevel: 'Secondary / Class 9-10',
    price: 350,
    isFree: false,
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'b5',
    title: 'Admission Math Shortcut Guide',
    author: 'Ayesha Siddiqua',
    description: 'Essential shortcut techniques, approximation methods, and fast calculation strategies for engineering and university admission tests.',
    category: 'Admission Books',
    mainCategory: 'Books Corner',
    subCategory: 'Admission Books',
    classOrLevel: 'Admission Candidate',
    price: 380,
    isFree: false,
    coverImage: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'b6',
    title: 'O Level Mathematics Practice Notes',
    author: 'Mathemzi Edu Editorial',
    description: 'Topical practice notes for Cambridge O Level Mathematics covering all syllabus components with past paper references.',
    category: 'Academic Books',
    mainCategory: 'Books Corner',
    subCategory: 'Academic Books',
    classOrLevel: 'O Level',
    price: 300,
    isFree: false,
    coverImage: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'b7',
    title: 'A Level Pure Math Formula Sheet',
    author: 'Prof. Anisul Islam',
    description: 'Comprehensive formula reference for A Level Pure Mathematics 1 & 2 with key theorems and identities.',
    category: 'Formula Sheets',
    mainCategory: 'Books Corner',
    subCategory: 'Formula Sheets',
    classOrLevel: 'A Level',
    price: 0,
    isFree: true,
    coverImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    downloadUrl: '#',
  },
  {
    id: 'b8',
    title: 'Mathematics in Nature Visual Guide',
    author: 'Mathemzi Edu Editorial',
    description: 'A beautifully illustrated guide to mathematical patterns in nature — Fibonacci, golden ratio, fractals, symmetry, and geometry in the natural world.',
    category: 'PDF Resources',
    mainCategory: 'Books Corner',
    subCategory: 'PDF Resources',
    classOrLevel: 'All Levels',
    price: 0,
    isFree: true,
    coverImage: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1600&auto=format&fit=crop',
    downloadUrl: '#',
  },
];

export const MATHEMATICS_NATURE_CONTENT = [
  {
    id: 'mn1',
    title: 'Fibonacci Sequence in Nature',
    topic: 'Nature Patterns',
    emoji: '🐚',
    description: 'The Fibonacci sequence (0, 1, 1, 2, 3, 5, 8, 13, 21…) appears in the spiral arrangement of sunflower seeds, pinecones, nautilus shells, and even the branching of trees. Each number is the sum of the two preceding ones, creating a growth pattern optimized for packing and efficiency.',
    image: 'https://images.unsplash.com/photo-1518495973-0bac4b7c6b9f?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'mn2',
    title: 'The Golden Ratio — Phi (φ)',
    topic: 'Nature Patterns',
    emoji: '✨',
    description: 'The Golden Ratio (approximately 1.618) appears in the proportions of the human face, the Parthenon, the Mona Lisa, and countless natural forms. It is derived from the Fibonacci sequence and is often associated with visual harmony and aesthetic perfection.',
    image: 'https://images.unsplash.com/photo-1551986782-d0169b3f8fa7?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'mn3',
    title: 'Symmetry in Living Organisms',
    topic: 'Visual Learning',
    emoji: '🦋',
    description: 'Bilateral symmetry (mirror symmetry) is found in butterflies, humans, and most animals. Radial symmetry appears in starfish, flowers, and snowflakes. Mathematics helps us classify and understand these symmetric patterns that define life on Earth.',
    image: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'mn4',
    title: 'Fractals — Infinite Patterns',
    topic: 'Real-life Mathematics',
    emoji: '❄️',
    description: 'Fractals are infinitely repeating patterns that look similar at any scale. Snowflakes, fern leaves, lightning bolts, coastlines, and blood vessels all exhibit fractal properties. Benoit Mandelbrot introduced fractal geometry to describe these "rough" natural shapes that Euclidean geometry cannot capture.',
    image: 'https://images.unsplash.com/photo-1504608524841-42fe6f032b4b?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'mn5',
    title: 'Honeycomb Geometry — Hexagons',
    topic: 'Visual Learning',
    emoji: '🐝',
    description: 'Bees build hexagonal honeycomb cells because hexagons are the most efficient shape for tessellation — they use the least wax while maximizing storage space. This is a real-world example of mathematical optimization in nature.',
    image: 'https://images.unsplash.com/photo-1568572933382-74d440642117?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'mn6',
    title: 'Waves, Sound, and Sine Functions',
    topic: 'Real-life Mathematics',
    emoji: '🌊',
    description: 'Ocean waves, sound waves, and light waves all follow sinusoidal patterns described by sine and cosine functions. The mathematics of waves explains everything from music to radio signals to earthquake propagation.',
    image: 'https://images.unsplash.com/photo-1519961655809-34fa186820f1?q=80&w=1600&auto=format&fit=crop',
  },
  {
    id: 'mn7',
    title: 'Mathematics in Flower Petals',
    topic: 'Articles',
    emoji: '🌻',
    description: 'Many flowers have a Fibonacci number of petals: lilies have 3, buttercups have 5, delphiniums have 8, marigolds have 13, and daisies often have 34, 55, or even 89 petals. This is nature following mathematical rules.',
    image: 'https://images.unsplash.com/photo-1490750967868-88aa4f44baee?q=80&w=1600&auto=format&fit=crop',
  },
];

export const studentStats: StudentStats = {
  activeCourses: 2,
  completedCourses: 4,
  upcomingExams: 1,
  certificates: 3,
  averageScore: '85%',
};

export const adminStats: AdminStats = {
  totalStudents: 12450,
  activeCourses: 35,
  totalRevenue: '৳ 12,50,000',
  upcomingExams: 8,
};
