import type { AdminStats, Article, Course, Exam, StudentStats } from './types';

export const courses: Course[] = [
  {
    id: '1',
    title: 'Complete Mathematics Olympiad Preparation',
    instructor: 'Dr. Hasan Rahman',
    price: 2500,
    duration: '12 Weeks',
    lessons: 48,
    rating: 4.8,
    category: 'Olympiad',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    description: 'Master number theory, combinatorics, algebra, and geometry for national and international math olympiads.',
    level: 'Advanced',
    enrolled: 2450,
    outcomes: [
      'Advanced problem solving techniques',
      'Number theory and combinatorics foundations',
      'Geometry proof strategy',
      'Timed olympiad practice routines',
    ],
    curriculum: [
      { title: 'Foundations of Number Theory', lessons: 5, time: '2h 10m' },
      { title: 'Algebraic Identities & Equations', lessons: 8, time: '3h 45m' },
      { title: 'Combinatorics & Probability', lessons: 6, time: '2h 30m' },
      { title: 'Geometric Properties', lessons: 7, time: '3h 15m' },
    ],
  },
  {
    id: '2',
    title: 'Academic Mathematics: HSC First Paper',
    instructor: 'Prof. Anisul Islam',
    price: 1500,
    duration: '8 Weeks',
    lessons: 32,
    rating: 4.6,
    category: 'Academic Maths',
    image: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?q=80&w=1600&auto=format&fit=crop',
    description: 'A complete HSC Mathematics First Paper guide with board-focused examples and real-world applications.',
    level: 'Intermediate',
    enrolled: 3180,
    outcomes: [
      'Full HSC first paper syllabus coverage',
      'Step-by-step calculus and algebra practice',
      'Board-style written answer patterns',
      'Weekly model test review',
    ],
    curriculum: [
      { title: 'Functions and Graphs', lessons: 6, time: '2h 40m' },
      { title: 'Matrices and Determinants', lessons: 5, time: '2h 15m' },
      { title: 'Differentiation', lessons: 9, time: '4h 10m' },
      { title: 'Integration Practice', lessons: 8, time: '3h 50m' },
    ],
  },
  {
    id: '3',
    title: 'Job Math Success Masterclass',
    instructor: 'Ayesha Siddiqua',
    price: 2000,
    duration: '10 Weeks',
    lessons: 40,
    rating: 4.9,
    category: 'Career',
    image: 'https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1600&auto=format&fit=crop',
    description: 'Shortcut tricks, problem-solving techniques, and previous-year question breakdowns for competitive job exams.',
    level: 'Job Prep',
    enrolled: 1890,
    outcomes: [
      'Fast arithmetic and mental math systems',
      'Question pattern recognition',
      'Previous-year solution breakdown',
      'Mock-test time management',
    ],
    curriculum: [
      { title: 'Arithmetic Speed Systems', lessons: 7, time: '3h 00m' },
      { title: 'Profit, Loss and Percentage', lessons: 8, time: '3h 25m' },
      { title: 'Geometry Shortcuts', lessons: 5, time: '2h 05m' },
      { title: 'Full Mock Analysis', lessons: 6, time: '2h 50m' },
    ],
  },
  {
    id: '4',
    title: 'Mathematics and Islam: A Harmonious View',
    instructor: 'Shaikh Tariqul',
    price: 0,
    duration: '4 Weeks',
    lessons: 12,
    rating: 5.0,
    category: 'Mathematics and Islam',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    description: 'Explore mathematical order, golden-ratio thinking, and the contributions of Islamic scholars.',
    level: 'Insight',
    enrolled: 920,
    outcomes: [
      'Islamic Golden Age mathematics overview',
      'Patterns, proportion and symmetry',
      'History-based reflective learning',
      'Applied examples from architecture and nature',
    ],
    curriculum: [
      { title: 'Numbers, Order and Reflection', lessons: 3, time: '1h 20m' },
      { title: 'Islamic Scholars and Algebra', lessons: 4, time: '1h 45m' },
      { title: 'Geometry in Art and Nature', lessons: 3, time: '1h 30m' },
      { title: 'Guided Reading Sessions', lessons: 2, time: '55m' },
    ],
  },
];

export const exams: Exam[] = [
  {
    id: '1',
    title: 'National Math Olympiad Practice Test 1',
    category: 'Olympiad',
    type: 'MCQ',
    fee: 100,
    date: '15 Nov, 2026',
    duration: '60 Mins',
    totalMarks: 50,
    syllabus: 'Number Theory, Algebra',
  },
  {
    id: '2',
    title: 'HSC Final Model Test - Calculus',
    category: 'Academic Maths',
    type: 'Written',
    fee: 150,
    date: '20 Nov, 2026',
    duration: '120 Mins',
    totalMarks: 100,
    syllabus: 'Differentiation, Integration',
  },
  {
    id: '3',
    title: 'Govt Job Math Pre-Assessment',
    category: 'Career',
    type: 'MCQ',
    fee: 50,
    date: '25 Nov, 2026',
    duration: '45 Mins',
    totalMarks: 40,
    syllabus: 'Percentages, Profit & Loss, Geometry',
  },
];

export const articles: Article[] = [
  {
    id: '1',
    title: 'The Philosophy of Numbers: Why Math Matters',
    description: 'A clear look at how numbers shape logic, pattern recognition, and disciplined thinking.',
    author: 'Dr. Hasan Rahman',
    date: 'Oct 12, 2026',
    category: 'Articles',
    image: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=1600&auto=format&fit=crop',
    content: 'Mathematics is more than formula memorization. It trains the mind to notice structure, compare possibilities, and move from confusion to clarity.\n\nFor students, this habit matters in exams and in real life. A strong mathematical foundation builds patience, precision, and confidence.',
  },
  {
    id: '2',
    title: 'Overcoming the Fear of Mathematics',
    description: 'Practical habits that help students move from anxiety to steady problem-solving confidence.',
    author: 'Ayesha Siddiqua',
    date: 'Oct 18, 2026',
    category: 'Career',
    image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1600&auto=format&fit=crop',
    content: 'Fear usually grows when students see mathematics as a race. The better approach is to slow down, identify the exact step that feels unclear, and practice that step repeatedly.\n\nSmall wins matter. One solved problem can become the evidence a learner needs to try the next one.',
  },
  {
    id: '3',
    title: 'How to Master Viva Presentations',
    description: 'A preparation framework for speaking clearly under pressure in academic and career settings.',
    author: 'Prof. Anisul Islam',
    date: 'Nov 01, 2026',
    category: 'Public Speaking',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?q=80&w=1600&auto=format&fit=crop',
    content: 'Good viva answers are structured, short, and honest. Start with the direct answer, add one supporting reason, then stop before the answer becomes unclear.\n\nPractice with a timer and record yourself. You will notice filler words, weak openings, and places where your explanation needs a cleaner example.',
  },
];

export const studentStats: StudentStats = {
  activeCourses: 2,
  completedCourses: 4,
  upcomingExams: 1,
  certificates: 3,
  averageScore: '85%',
};

export const adminStats: AdminStats = {
  totalStudents: 12450,
  activeCourses: 35,
  totalRevenue: '৳ 12,50,000',
  upcomingExams: 8,
};
