import type { SiteSettings } from './types';

export const DEFAULT_SITE_SETTINGS: SiteSettings = {
  siteName: 'Mathenzi Edu',
  shortName: 'Mathenzi',
  tagline: 'Master Mathematics with Logic, Practice & Confidence',
  banglaTagline: 'গণিত হোক সহজ, যুক্তিতে হোক শক্তিশালী',
  logoUrl: '',
  faviconUrl: '',
  heroBadge: "Bangladesh's Premium Math Platform",
  heroTitle: 'Master Mathematics for School, Olympiad & Admission Success',
  heroSubtitle: 'Mathenzi Edu helps Bangladeshi students build strong mathematical foundations through structured courses, practice exams, books, progress tracking, and expert-guided learning.',
  heroBtn1Text: 'Explore Courses',
  heroBtn1Link: '/courses',
  heroBtn2Text: 'Start Practice Exam',
  heroBtn2Link: '/exams',
  heroBtn3Text: 'Browse Books',
  heroBtn3Link: '/books',
  trustSectionTitle: 'Why Learn With Mathenzi Edu',
  trustSectionItems: [
    'Structured learning paths for all levels',
    'Practice-based exam preparation',
    'Manual bKash verified enrollment',
    'Progress tracking & completion certificates',
    'Admin-managed content & quality control',
  ],
  aboutTitle: 'About Mathenzi Edu',
  aboutIntro: 'Welcome to Mathenzi Edu. We believe in learning mathematics with logic, beauty, faith, and real-life applications.',
  missionTitle: 'Our Mission',
  missionText: 'To provide a comprehensive, engaging, and premium platform where students and professionals can master mathematical concepts. We break complex problems into understandable, logical steps that foster true comprehension and love for the subject.',
  visionTitle: 'Our Vision',
  visionText: 'To become a leading digital platform for mathematical learning that integrates logic and real-world utility, empowering learners to reach academic and career excellence.',
  aboutFeatures: [
    'Advanced Learning Management System (LMS)',
    'Interactive video lessons and live classes',
    'Practice exams with real-time analytics',
    'Detailed progress tracking and personalized feedback',
    'Confidence-building and problem-solving training',
  ],
  contactPageTitle: 'Talk to Mathenzi Edu',
  contactPageSubtitle: 'Course guidance, exam registration, mentor support, or partnership questions. Send a note and the team will follow up.',
  contactPhone: '+880 1700 000000',
  contactEmail: 'support@mathenziedu.com',
  contactAddress: 'Dhaka, Bangladesh',
  supportHours: 'Saturday – Thursday, 10:00 AM – 8:00 PM (BST)',
  bkashNumber: '01XXXXXXXXX',
  bkashAccountType: 'Merchant',
  bkashInstructions: [
    'Go to your bKash app and select "Send Money".',
    'Enter our bKash number shown above.',
    'Enter the exact payable amount from your order.',
    'Write your Order ID in the reference field (recommended).',
    'Enter your bKash PIN and confirm the payment.',
    'Copy the Transaction ID (TrxID) from the bKash confirmation message.',
    'Return to this page and submit your Transaction ID and bKash number below.',
  ],
  paymentSupportContact: 'support@mathenziedu.com',
  paymentNote: 'Please send the payable amount to our bKash number. After payment, submit your bKash Transaction ID from your dashboard or payment section. Our admin team will verify the payment manually. Access will be activated after verification.',
  facebookUrl: 'https://facebook.com/mathenziedu',
  youtubeUrl: 'https://youtube.com/@mathenziedu',
  instagramUrl: 'https://instagram.com/mathenziedu',
  linkedinUrl: '',
  twitterUrl: 'https://twitter.com/mathenziedu',
  seoTitle: 'Mathenzi Edu | Premium Mathematics Learning Platform in Bangladesh',
  seoDescription: 'Master Mathematics for School, Olympiad & Admission Success. Bangladesh-focused mathematics learning ecosystem.',
  seoKeywords: 'mathematics learning Bangladesh, math courses, olympiad preparation, admission math',
  seoOgImage: 'https://mathenziedu.com/og.png',
  privacyIntro: 'Mathenzi Edu collects only the account and learning information needed to provide courses, exams, support, and progress tracking.',
  privacyDataText: 'Basic profile, saved articles, progress, enrollment, and support details may be stored to personalize the platform.',
  privacySecurityText: 'We use verified access rules, admin-only controls, and trusted providers to protect learner information.',
  termsIntro: 'By using Mathenzi Edu, learners agree to use course materials fairly, keep account access private, and follow exam rules.',
  termsAccessText: 'Course access is tied to the registered account. Sharing paid course access outside the account is not permitted.',
  termsPaymentsText: 'Payments are manually verified. Exam, refund, and certification decisions follow the information shown with the relevant product.',
  footerText: 'Master Mathematics with Logic, Practice & Confidence. Your complete Bangladesh-focused learning ecosystem.',
  updatedAt: Date.now(),
};
